language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false

git:
    submodules: true

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/homie-ds18b20-1wire.ino

install:
    - pip install -U platformio
    # - platformio lib -g install DallasTemperature PubSubClient Onewire Homie
    - platformio lib -g install DallasTemperature PubSubClient Onewire https://github.com/marvinroger/homie-esp8266/archive/develop.zip

script:
    - platformio ci --board=nodemcu
